name: daily-next

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-22.04

    container:
      image: debian:latest
      volumes:
        - /proc:/proc
      options: --privileged

    steps:
    - name: Clone build scripts
      uses: actions/checkout@v4

    - name: Build and upload daily .iso
      run: |
        ./workflows.sh etc/terraform-daily-8.0-azure.conf
    - name: Upload ISO to GitHub Actions
      uses: actions/upload-artifact@v4
      with:
        name: ISO 8.0 daily
        path: builds/amd64/*
